"""Update models

Revision ID: de5662ff628f
Revises: 3a574c624d05
Create Date: 2019-07-03 09:59:06.816660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de5662ff628f'
down_revision = '3a574c624d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch', sa.String(), nullable=True))
    op.drop_column('pitches', 'profile_pic')
    op.drop_column('pitches', 'time')
    op.drop_column('pitches', 'name')
    op.drop_column('pitches', 'email')
    op.drop_column('pitches', 'bio')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('bio', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('profile_pic', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'pitch')
    # ### end Alembic commands ###
